### ISSUE TITLE
[question] Is there a way to trigger the plugin if the user was created anonymously in Firebase initially but adds their email id later?

### ISSUE THREAD

**Issue by arjunbansal** [mailchimp/Firebase#17]
Currently, we do not have email information at the time the Firebase auth id is created, but this is collected later. Is there a way to trigger the add new user behavior in Mailchimp when that email information is added rather than when the initial anonymous id is created?

**Comment by bradatmailchimp** [comment]
Hi @arjunbansal, this is a really great idea, but Mailchimp requires an email when creating the user and due to how we are using firebase auth, we cannot avoid the calls and trigger them again later. We will definitely keep this in mind as this is really valuable user feedback! Sorry we cannot support this at this time and thank you again.

**Comment by arjunbansal** [comment]
Thanks for the reply.
