### ISSUE TITLE
auth-mailchimp-sync: Plugin fails to add user on linkWithCredential 

### ISSUE THREAD

**Issue by dackers86** [mailchimp/Firebase#26]
Original issue from https://github.com/firebase/extensions/issues/630

**Comment by barticus** [comment]
As per [this comment](https://github.com/firebase/extensions/issues/630#issuecomment-811821806), onCreate is only triggered when the [user account is first created](https://firebase.google.com/docs/functions/auth-events#trigger_a_function_on_user_creation). For people with this issue, suggested solutions:

- Persist data to firestore as well, and the change will be detected, OR
- Create a new user once this detail is known, rather than re-using the anonymous one. Clean up the anonymous one if you can.
